### ISSUE TITLE
[Задача, 24.10.2016] GET-запрос, разбор HTTP-заголовков

### ISSUE THREAD

**Issue by DmitryKuk** [IDB-15-15/Network#4]
Задача:
- Изучить виды заголовков.
- Определить, какие заголовки необходимо отправлять серверу, и какие важны при приёме ответа.
- Усовершенствовать класс-результат загрузки, чтобы его объекты были способны содержать полученные заголовки (предусмотреть методы для их получения, если другим командам вдруг понадобится).
- Научиться выделять необходимые для сетевой части заголовки (например, код ошибки и Content-Length).
- Реализовать функцию, отправляющую GET-запрос с необходимыми заголовками и получающую ответ. Результатом работы функции должен быть объект того самого волшебного класса.

Дополнительная задача:
- Изучить свойства предлагаемых контейнеров (4 разновидности map-а).
- Самостоятельно принять решение о целесообразности применения какого-либо из них для хранения разобранных HTTP-заголовков.
  - Требуется ли упорядоченность?
  - Требуется ли возможность хранить повторяющиеся ключи?
- Обсудить принятое решение со своей командой.
- При необходимости скорректировать принятое решение.
- Реализовать в коде решение данной задачи.
- О принятом решении написать в комментариях к данной задаче.

Ссылки:
- [Список заголовков HTTP](https://ru.wikipedia.org/wiki/Список_заголовков_HTTP)
- [std::unordered_map, std::unordered_multimap](http://www.cplusplus.com/reference/unordered_map/)
- [std::map, std::multimap](http://www.cplusplus.com/reference/map/)

**Comment by dimasbr** [comment]
Списки заголовков-это, конечно, классно и хоть немного информативно, но можно узнать-что это вообще такое и что они делают?

**Comment by DmitryKuk** [comment]
Прочитайте эти статьи:
- [HTTP](https://ru.wikipedia.org/wiki/HTTP#.D0.A1.D1.82.D1.80.D1.83.D0.BA.D1.82.D1.83.D1.80.D0.B0_.D0.BF.D1.80.D0.BE.D1.82.D0.BE.D0.BA.D0.BE.D0.BB.D0.B0), начиная со "Структура протокола".
- [Заголовки HTTP](https://ru.wikipedia.org/wiki/Заголовки_HTTP).

HTTP-заголовки позволяют клиенту общаться с сервером. Отправлять серверу дополнительную информацию, получать от сервера сообщения об ошибках и т.д.
Изучите протокол HTTP.
